<?php

/**
 * @file
 * Contains custom_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.custom_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a custom block with greeting message.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function custom_block_theme() {
  return [
    'custom_block_greeting' => [
      'variables' => [
        'message' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function custom_block_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'custom_block/custom_block';
}
